// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (answer, expires_at)
VALUES ($1, $2)
RETURNING id, answer, guesses, solved, created_at, expires_at
`

type CreateGameParams struct {
	Answer    string
	ExpiresAt time.Time
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame, arg.Answer, arg.ExpiresAt)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Answer,
		pq.Array(&i.Guesses),
		&i.Solved,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, answer, guesses, solved, created_at, expires_at FROM games
WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Answer,
		pq.Array(&i.Guesses),
		&i.Solved,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET guesses = $1, solved = $2
WHERE id = $3
RETURNING id, answer, guesses, solved, created_at, expires_at
`

type UpdateGameParams struct {
	Guesses []string
	Solved  bool
	ID      uuid.UUID
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, updateGame, pq.Array(arg.Guesses), arg.Solved, arg.ID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Answer,
		pq.Array(&i.Guesses),
		&i.Solved,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
