// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Game struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Answer    string
	Guesses   []string
	Solved    bool
	CreatedAt time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
}
